version: '3.8'

services:
  db:
    image: postgres:15
    container_name: gPortfolio-db
    restart: always
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network
    environment:
      POSTGRES_PASSWORD: "${PASSWORD}"
      POSTGRES_USER: "${USER}"
      POSTGRES_DB: "${DB}"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: gPortfolio-pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ashley.desbravador@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - app_network

  app:
    build: .
    container_name: gPortfolio-app
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8082:8082"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge