server:
  port: 8083

spring:
  application:
    name:gerenciamentoportfolio

  config:
    import: "optional:classpath:.env"

  jackson:
    serialization:
      WRITE_ENUMS_USING_TO_STRING: true
    deserialization:
      READ_ENUMS_USING_TO_STRING: true


  datasource:
    url: ${DATASOURCE_URL:NOT_FOUND}
    username: ${USER}
    password: ${PASSWORD}
    driver-class-name: ${DRIVER}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true


  docker:
    compose:
      enabled: false

  logging:
    level:
      root: info
      io.github.ashleysaintlouis.gerenciamentoportfolio: DEBUG
      org.springframework.web: debug
      org.hibernate: error
      org.springframework.security: trace
      org.springframework.web.servlet.DispatcherServlet: trace
      org.springframework.core.env: DEBUG
      org.springframework.boot.context.config: DEBUG
    file:
      name: logs/minha-aplicacao.log